In [1]:
import pandas as pd

In [3]:
df = pd.read_excel(r"C:\Users\Admin\Downloads\Python\Pandas\data.xlsx")

In [4]:
df.head()

,Employee_ID,Employee_Name,Department,Salary,Joining_Date,Email,Phone,City
0,101,Rahul,IT,50000,12-01-2022,rahul@gmail.com,9.876543e+09,Mumbai
1,102,Anita,HR,NaN,15/02/2021,anita@gmail,9.876500e+04,Delhi
2,103,Suresh,it,60000,2022-03-18,suresh@gmail.com,9.876543e+09,Pune
3,104,NaN,Finance,55000,18-04-2020,finance@gmail.com,9.876543e+09,Mumbai
4,105,Neha,NaN,52000,04-31-2021,neha@gmail.com,NaN,Chennai

In [5]:
df.tail()

,Employee_ID,Employee_Name,Department,Salary,Joining_Date,Email,Phone,City
5,106,Amit,HR,52000,12-01-22,amit@gmail.com,9.876543e+09,Delhi
6,107,Priya,IT,70000,2021/07/25,priya@gmail.com,9.876543e+09,Bangalore
7,108,Rohit,Finance,70k,01-09-2020,rohitgmail.com,9.876543e+09,Mumbai
8,109,Kiran,HR,48000,2020-11-11,kiran@gmail.com,9.876543e+09,Hyderabad
9,110,Kiran,HR,48000,2020-11-11,kiran@gmail.com,9.876543e+09,Hyderabad

In [6]:
df.shape

(10, 8)

In [7]:
df.sample(3)

,Employee_ID,Employee_Name,Department,Salary,Joining_Date,Email,Phone,City
1,102,Anita,HR,NaN,15/02/2021,anita@gmail,9.876500e+04,Delhi
9,110,Kiran,HR,48000,2020-11-11,kiran@gmail.com,9.876543e+09,Hyderabad
3,104,NaN,Finance,55000,18-04-2020,finance@gmail.com,9.876543e+09,Mumbai

In [8]:
df.isnull().sum()

Employee_ID      0
Employee_Name    1
Department       1
Salary           1
Joining_Date     0
Email            0
Phone            1
City             0
dtype: int64

In [9]:
df.dropna(inplace=True)

In [10]:
df

,Employee_ID,Employee_Name,Department,Salary,Joining_Date,Email,Phone,City
0,101,Rahul,IT,50000,12-01-2022,rahul@gmail.com,9.876543e+09,Mumbai
2,103,Suresh,it,60000,2022-03-18,suresh@gmail.com,9.876543e+09,Pune
5,106,Amit,HR,52000,12-01-22,amit@gmail.com,9.876543e+09,Delhi
6,107,Priya,IT,70000,2021/07/25,priya@gmail.com,9.876543e+09,Bangalore
7,108,Rohit,Finance,70k,01-09-2020,rohitgmail.com,9.876543e+09,Mumbai
8,109,Kiran,HR,48000,2020-11-11,kiran@gmail.com,9.876543e+09,Hyderabad
9,110,Kiran,HR,48000,2020-11-11,kiran@gmail.com,9.876543e+09,Hyderabad

In [11]:
df.shape

(7, 8)

In [12]:
df.describe()

       Employee_ID         Phone
count     7.000000  7.000000e+00
mean    106.285714  9.876543e+09
std       3.251373  2.370453e+00
min     101.000000  9.876543e+09
25%     104.500000  9.876543e+09
50%     107.000000  9.876543e+09
75%     108.500000  9.876543e+09
max     110.000000  9.876543e+09