In [54]:
import pandas as pd

In [55]:
df = pd.read_csv(r"C:\Users\Admin\Downloads\Python\Pandas\Data_cleaning.csv")

In [56]:
df.head()

,Order_ID,Customer Name,Age,Email Address,Order Date,Amount Paid ($),Product Details,Shipping City,Order Status,Quantity Ordered,Remarks,Phone Number
0,101.0,john SMITH,28,john.smith@email.com,2023/04/12,150.25,Laptop - 16GB,New york,delivered,1,Good customer,9876543210
1,102.0,ANNA Jones,NaN,annajones@sample.com,04-15-2023,NaN,Mobile - 64GB,new york,Delivered,2,NaN,NaN
2,103.0,Sam@@Patel,35,sam@@patel.com,2023.05.10,250.75,Laptop - 8GB,MUMBAI,Delivered,1,Invalid email address,9999999999
3,104.0,NaN,-5,rohan@gmail.com,05/13/2023,130.50,Headphone - Wireless,mumbai,cancelled,3,Missing name,12345678
4,105.0,Priya Sharma,29,priyasharma@email.com,2023-06-01,420.00,Camera - 20MP,Delhi,Returned,1,RETURNED,NaN

In [57]:
df.describe()

         Order_ID  Amount Paid ($)
count   10.000000        10.000000
mean   105.000000     15307.324000
std      2.581989     47326.807896
min    101.000000       -50.000000
25%    103.250000       175.375000
50%    105.000000       385.375000
75%    106.750000       555.000000
max    109.000000    150000.000000

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          10 non-null     float64
 1   Customer Name     9 non-null      object
 2   Age               9 non-null      object
 3   Email Address     11 non-null     object
 4   Order Date        10 non-null     object
 5   Amount Paid ($)   10 non-null     float64
 6   Product Details   10 non-null     object
 7   Shipping City     11 non-null     object
 8   Order Status      10 non-null     object
 9   Quantity Ordered  10 non-null     object
 10  Remarks           9 non-null      object
 11  Phone Number      9 non-null      object
dtypes: float64(2), object(10)
memory usage: 1.2+ KB

In [59]:
df.duplicated().sum()

np.int64(0)

In [60]:
df["Age"].fillna(0, inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_18776\2097341988.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(0, inplace=True)

In [62]:
#Replace Thirty with 30
df["Age"].replace('Thirty', 30, inplace=True)

In [63]:
#Change the data type of Age
df["Age"]=df["Age"].astype(int)

In [65]:
#Delete the row that is negative 
df2 = df[df["Age"]>0]

In [38]:
df["Product Details"].tail()

6        Laptop - 32GB
7                  NaN
8     Smartwatch - GPS
9        Laptop - 64GB
10          USB - 32GB
Name: Product Details, dtype: object

In [66]:
df2["Product Details"].fillna("Smart Watch", inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_18776\709742647.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2["Product Details"].fillna("Smart Watch", inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18776\709742647.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Product Details"].fillna("Smart Watch", inplace=True)

In [41]:
df["Amount Paid ($)"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 11 entries, 0 to 10
Series name: Amount Paid ($)
Non-Null Count  Dtype
--------------  -----
10 non-null     float64
dtypes: float64(1)
memory usage: 220.0 bytes

In [67]:
df2["Amount Paid ($)"].fillna(0, inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_18776\3971520997.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2["Amount Paid ($)"].fillna(0, inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18776\3971520997.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Amount Paid ($)"].fillna(0, inplace=True)

In [68]:
df2 = df[df["Amount Paid ($)"]>0]
df2.tail()

,Order_ID,Customer Name,Age,Email Address,Order Date,Amount Paid ($),Product Details,Shipping City,Order Status,Quantity Ordered,Remarks,Phone Number
5,105.0,Priya Sharma,29,priyasharma@email.com,2023-06-01,420.00,Camera - 20MP,Delhi,Returned,1,Duplicate order,9999999999
6,106.0,RAJESH kumar,145,rajeshkumar@email.com,"Jun 10, 2023",800.99,Laptop - 32GB,delhi,shipped,NaN,Quantity missing,88888abcde
7,107.0,Meena,0,meena@site,2023-15-06,350.75,NaN,Bangalore,Cancelled,2,NaN,98765
8,NaN,NaN,34,test@invalid.com,NaN,600.00,Smartwatch - GPS,bangalore,NaN,1,Missing order ID,0000000000
9,108.0,Naresh Verma,41,naresh@email.com,2023-07-20,150000.00,Laptop - 64GB,New Delhi,Delivered,1,Unusually high amount,9876543210

In [77]:
df2.tail()

,Order_ID,Customer Name,Age,Email Address,Order Date,Amount Paid ($),Product Details,Shipping City,Order Status,Quantity Ordered,Remarks
5,105.0,Priya Sharma,29,priyasharma@email.com,2023-06-01,420.00,Camera - 20MP,Delhi,Returned,1,Duplicate order
6,106.0,RAJESH kumar,145,rajeshkumar@email.com,"Jun 10, 2023",800.99,Laptop - 32GB,delhi,Shipped,NaN,Quantity missing
7,107.0,Meena,0,meena@site,2023-15-06,350.75,NaN,Bangalore,Cancelled,2,NaN
8,NaN,NaN,34,test@invalid.com,NaN,600.00,Smartwatch - GPS,bangalore,Nan,1,Missing order ID
9,108.0,Naresh Verma,41,naresh@email.com,2023-07-20,150000.00,Laptop - 64GB,New Delhi,Delivered,1,Unusually high amount

In [79]:
df2.drop(axis=0, index=8, inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_18776\1921924251.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(axis=0, index=8, inplace=True)

In [80]:
df2.shape

(8, 11)

In [71]:
df.shape

(11, 12)

In [72]:
df2.drop(columns="Phone Number", axis=1, inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_18776\3702331248.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(columns="Phone Number", axis=1, inplace=True)

In [46]:
df2.head()

,Order_ID,Customer Name,Age,Email Address,Order Date,Amount Paid ($),Product Details,Shipping City,Order Status,Quantity Ordered,Remarks
0,101.0,john SMITH,28,john.smith@email.com,2023/04/12,150.25,Laptop - 16GB,New york,delivered,1,Good customer
2,103.0,Sam@@Patel,35,sam@@patel.com,2023.05.10,250.75,Laptop - 8GB,MUMBAI,Delivered,1,Invalid email address
3,104.0,NaN,-5,rohan@gmail.com,05/13/2023,130.50,Headphone - Wireless,mumbai,cancelled,3,Missing name
4,105.0,Priya Sharma,29,priyasharma@email.com,2023-06-01,420.00,Camera - 20MP,Delhi,Returned,1,RETURNED
5,105.0,Priya Sharma,29,priyasharma@email.com,2023-06-01,420.00,Camera - 20MP,Delhi,Returned,1,Duplicate order

In [48]:
df2["Remarks"].fillna("No Remark", inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_18776\2990974069.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2["Remarks"].fillna("No Remark", inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18776\2990974069.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Remarks"].fillna("No Remark", inplace=True)

In [73]:
def capitalize_status(s):
    return str(s).strip().capitalize()

In [74]:
df2["Order Status"] = df2["Order Status"].apply(capitalize_status)

C:\Users\Admin\AppData\Local\Temp\ipykernel_18776\189904031.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Order Status"] = df2["Order Status"].apply(capitalize_status)

In [75]:
df2["Order Status"].head()

0    Delivered
2    Delivered
3    Cancelled
4     Returned
5     Returned
Name: Order Status, dtype: object

In [81]:
df2.shape

(8, 11)