<a href="https://colab.research.google.com/github/anuragpatil811/Applied-Data-Analysis/blob/main/DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["Amit", "Priya", "Rahul", "Neha"],
    "Age": [21, 22, 30, 54],
    "Marks": [85, 90, 78, 92]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
print(df)

    Name  Age  Marks
0   Amit   21     85
1  Priya   22     90
2  Rahul   30     78
3   Neha   54     92

In [5]:
print(df["Marks"])

0    85
1    90
2    78
3    92
Name: Marks, dtype: int64

In [6]:
print(df[["Name", "Marks"]])

    Name  Marks
0   Amit     85
1  Priya     90
2  Rahul     78
3   Neha     92

In [8]:
high_scorer = df[df["Marks"]>80]
high_scorer

    Name  Age  Marks
0   Amit   21     85
1  Priya   22     90
3   Neha   54     92

In [9]:
df["Pass"] = df["Marks"] > 40
df

    Name  Age  Marks  Pass
0   Amit   21     85  True
1  Priya   22     90  True
2  Rahul   30     78  True
3   Neha   54     92  True

In [11]:
df_sorted = df.sort_values(by="Marks", ascending=False)
df_sorted

    Name  Age  Marks  Pass
3   Neha   54     92  True
1  Priya   22     90  True
0   Amit   21     85  True
2  Rahul   30     78  True

In [12]:
df.describe()

             Age      Marks
count   4.000000   4.000000
mean   31.750000  86.250000
std    15.370426   6.238322
min    21.000000  78.000000
25%    21.750000  83.250000
50%    26.000000  87.500000
75%    36.000000  90.500000
max    54.000000  92.000000